import { type DMMF, type GeneratorOptions } from "@prisma/generator-helper";
import { promises as fs } from "fs";
import path from "path";
import { styleText } from "util";
import { parseConfig } from "./parse-config.js";

type NameMapping = Record<
  string,
  {
    tableName: string;
    schema: string | null;
    fields: Record<string, string>;
  }
>;

const FILE_HEADER = `
// 🔴️ AUTO-GENERATED FILE — DO NOT EDIT! 🔴
//
// This file is automatically generated by prisma-name-mapper.
// Do not edit this file directly.
`.trim();

const FIELD_NAME = "PrismaNameMapper";

const formatAsTypescriptConst = (object: object, constantName: string): string => {
  const jsonString = JSON.stringify(object, null, 2);
  const objectLiteralString = jsonString.replace(/"([^"]+)":/g, "$1:");

  return `${FILE_HEADER}\n\nexport const ${constantName} = ${objectLiteralString} as const;`;
};

const generateNameMapping = (models: readonly DMMF.Model[]): NameMapping => {
  const mappings: NameMapping = {};

  models.forEach(model => {
    mappings[model.name] = {
      tableName: model.dbName || model.name,
      schema: model.schema,
      fields: {},
    };
    model.fields.forEach(field => {
      if (field.kind === "scalar" || field.kind === "unsupported") {
        mappings[model.name].fields[field.name] = field.dbName || field.name;
      }
    });
  });

  return mappings;
};

export const onGenerate = async (options: GeneratorOptions) => {
  const config = parseConfig(options.generator);

  if (config.output === undefined) {
    throw new Error(
      styleText("red", `[Prisma Name Mapper] Error: The 'output' path is required.`),
    );
  }

  const nameMap = generateNameMapping(options.dmmf.datamodel.models);
  const fileContent = formatAsTypescriptConst(nameMap, FIELD_NAME);

  try {
    await fs.mkdir(path.dirname(config.output), { recursive: true });
    await fs.writeFile(config.output, fileContent);
  } catch (err) {
    console.log(styleText("red", `[Prisma Name Mapper] Error: The file couldn't be created.`));
    throw err;
  }
};
